// src/constants/categoryIcons.js

export const CATEGORY_ICONS = {
  AfricanMarket: "🌍",
  ArtsCrafts: "🎨",
  BusinessEntrepreneurship: "💼",
  Certifications: "📜",
  CreativeArtistic: "🎭",
  DigitalOnline: "💻",
  EducationTeaching: "📚",
  EmergingTechnology: "🚀",
  Engineering: "⚙️",
  EnvironmentalSustainability: "🌱",
  HealthWellness: "🏥",
  HomePractical: "🏠",
  LanguageCommunication: "💬",
  LegalRegulatory: "⚖️",
  LifestyleLeisure: "🎯",
  ManagementLeadership: "👔",
  MarketingBranding: "📈",
  MiscellaneousUnique: "🔧",
  "MusicPerforming Arts": "🎵",
  PersonalDevelopment: "🌟",
  ProfessionalBusiness: "💼",
  "SalesCustomer Service": "🛒",
  ScienceResearch: "🔬",
  SportsOutdoor: "⚽",
  TechnicalIT: "💻",
  WritingContent: "✍️",
};
